name: "Delegate Compute"
description: "UbiquityOS Delegated Compute Action"
outputs:
  result:
    description: "The result of a event handler"
    value: ${{ steps.mainHandler.outputs.result }}
runs:
  using: "node20"
  main: "dist/index.js"
