name: "Update Configuration and Build"

on:
  workflow_dispatch:
  push:

jobs:
  update:
    name: "Update Configuration & Build"
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: ubiquity-os/action-deploy-plugin@main
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
